- name: Creating HTTPS application
  hosts: localhost
  connection: local
  
#Environment variables defined
  environment:
    F5_USER: "{{ F5_Username }}"
    F5_PASSWORD: "{{ F5_Password }}"
    F5_SERVER_PORT: "{{ F5_Admin_Port }}" #"443"
    F5_VALIDATE_CERTS: "False"
    F5_SERVER: "{{ F5_IPAddress }}"
    
  vars:
    F5_VIP_Name: "{{ VIP_Application }}"

  tasks:
  - name: Collect BIG-IP facts on Virtual Server
    bigip_device_facts:
      gather_subset:
        - virtual-servers
    register: VS_Info

  - debug:
      msg: "{{ item.name }}"
    with_items: "{{ VS_Info.virtual_servers }}"

  - name: Create a redirect virtual server
    bigip_virtual_server:
      description: "Redirect Virtual server"
      name: "{{ item.name }}_http_redirect"
      destination: "{{item.destination_address}}"
      port: "80"
      all_profiles:
       - http
      all_rules:
       - _sys_https_redirect
    when: item.name == F5_VIP_Name
    with_items: "{{ VS_Info.virtual_servers }}"
