---

#Re-Deploy ASM policy
  - name: Create an LTM policy
    bigip_policy:
      provider: "{{provider}}"
      name: asm-policy
      state: present
    when: Blocked_URLs is defined or Blocked_IPs is defined

  - name: Import ASM policy
    bigip_asm_policy_import:
      provider: "{{provider}}"
      name: "{{ ASM_Policy_Name }}"
      source: "{{ ASM_Policy_File }}"
      force: yes
    when: Blocked_URLs is defined or Blocked_IPs is defined

  - name: Replace a forward action with an ASM action
    bigip_policy_rule:
      provider: "{{provider}}"
      policy: asm-policy
      name: rule1
      actions:
      - type: enable
        asm_policy: "{{ ASM_Policy_Name }}"
    when: Blocked_URLs is defined or Blocked_IPs is defined

  - name: Deploy Draft ASM policy
    bigip_policy:
      provider: "{{provider}}"
      name: asm-policy
      state: present
      rules:
      - rule1
    when: Blocked_URLs is defined or Blocked_IPs is defined

#Assign ASM Policy to VIP
  - name: Update the HTTPS Virtual Server
    bigip_virtual_server:
      provider: "{{provider}}"
      state: present
      description: "HTTPS Virtual Server"
      name: "{{ F5_VIP_Name }}_https_vip"
      destination: "{{ private_ip }}"
      port: "8082"
      pool: "{{ F5_VIP_Name }}_pool"
      snat: Automap
      profiles:
       - http
       - oneconnect
       - name: clientssl
         context: client-side
       - websecurity
      policies:
       - asm-policy
    when: F5_VIP_Name is defined

#Apply Draft ASM policy
  - name: Activate ASM Policy
    bigip_asm_policy_manage:
      provider: "{{provider}}"
      name: "{{ ASM_Policy_Name }}"
      active: yes

