---
# tasks file for ASM-Role
 - name: Check if Backup File Exists
   stat:
     path: /tmp/Use-Case-00-Backup.ucs
   register: backup_file
   tags:
     - restore

 - debug:
     msg: "{{backup_file.stat.exists}}"
   tags:
     - debug

 - name: Restore F5 Configuration
   include: f5_restore_config.yaml
   tags: 
     - restore
   when: backup_file.stat.exists == true

 - debug:
     msg: "Restore F5 Configuration FAILED do to backup file not found"
   when: backup_file.stat.exists == false
   tags:
     - restore

 - debug:
     msg: "Restore Completed, Ignore JSON Error.  Reported bug at https://github.com/F5Networks/f5-ansible/issues/1666"
   when: backup_file.stat.exists == true
   tags:
     - restore
   

