---
ec2_wait: yes
ec2_subnet: "172.16.0.0/16"
ssh_port: 22

control_type: "centos-tower"
webserver_type: "centos"

# Additional info needed by AWS ec2 modules
ec2_info:
  f5node:
    name: "F5 Networks Prelicensed Hourly BIGIP-13.1.0.7-0.0.1 - Best 25MBPS *"    
    product_code: "3ouya04g99e5euh4vbxtao1jz"
    size: t2.large
    os_type: linux
    disk_space: 40
    architecture: x86_64
    username: admin
