- name: Enabling or Disabling Nodes in BIG-IP
  hosts: lb
  connection: local
  gather_facts: false
  
#Environment variables defined
  environment:
    F5_USER: "{{ ansible_user }}"
    F5_PASSWORD: "{{ ansible_ssh_pass }}"
    F5_SERVER_PORT: "{{ F5_Admin_Port }}"
    F5_VALIDATE_CERTS: "False"
    F5_SERVER: "{{ private_ip }}"
    
  tasks:

    - name: Query BIG-IP facts
      bigip_device_facts:
        gather_subset:
        - nodes
      register: bigip_facts

    - name: DISABLE NODES
      bigip_node:
        name: "{{item.0}}"
        state: "disabled"
      when: F5_Node_State|lower  == "disabled" and item.0 == item.1.name
      with_nested: 
      - "{{ F5_Nodes }}"
      - "{{ bigip_facts.nodes }}"


    - name: ENABLE NODES
      bigip_node:
        name: "{{item}}"
        state: "enabled"
      when: F5_Node_State|lower  == "enabled" and item.0 == item.1.name
      with_nested:
      - "{{ F5_Nodes }}"
      - "{{ bigip_facts.nodes }}"

