---
- name: "Add Pool Members and/or Point to New Pool"
  hosts: lb
  gather_facts: false
  connection: local

#Environment variables defined
  environment:
    F5_USER: "{{ ansible_user }}"
    F5_PASSWORD: "{{ ansible_ssh_pass }}"
    F5_SERVER_PORT: "{{ F5_Admin_Port }}"
    F5_VALIDATE_CERTS: "False"
    F5_SERVER: "{{ private_ip }}"

  tasks:

  - name: Create a HTTPS Virtual Server with No Pool
    bigip_virtual_server:
      state: present
      description: "HTTPs Virtual Server"
      name: "{{ F5_VIP_Name }}_https_vip"
      destination: "{{ private_ip }}"
      port: "8084"
      snat: Automap
      profiles:
       - http
       - oneconnect
       - name: clientssl
         context: client-side
    when: F5_VIP_Name is defined

  - name: Create Pool
    bigip_pool:
     name: "{{ F5_VIP_Name }}_pool"
     lb_method: round-robin
     monitors: 
     - http
    when: F5_New_Pool_Members is defined and F5_New_Pool_Monitors is defined

  - name: Add pool member
    bigip_pool_member:
     pool: "{{ F5_VIP_Name }}_pool"
     name: "{{hostvars[item].inventory_hostname}}"
     host: "{{hostvars[item].private_ip}}"
     port: "80"
     description: "{{ F5_VIP_Name }}_pool"
    with_items: "{{ groups['webservers'] }}"
    when: F5_New_Pool_Members is defined
    
  - name: UPDATE A VIRTUAL SERVER
    bigip_virtual_server:
     name: "{{ F5_VIP_Name }}_https_vip"
     pool: "{{F5_VIP_Name}}_pool"
    when: F5_New_Pool_Members is defined

  - name: UPDATE A VIRTUAL SERVER With Pool (When No New Pool is Defined)
    bigip_virtual_server:
     name: "{{ F5_VIP_Name }}_https_vip"
     pool: "{{ F5_Pool_Name }}"
    when: F5_Pool_Name is defined and F5_New_Pool_Members is not defined

