- name: Enabling or Disabling LTM Nodes
  hosts: localhost
  connection: local
  
#Environment variables defined
  environment:
    F5_USER: "{{ F5_Username }}"
    F5_PASSWORD: "{{ F5_Password }}"
    F5_SERVER_PORT: "{{ F5_Admin_Port }}" #"443"
    F5_VALIDATE_CERTS: "False"
    F5_SERVER: "{{ F5_IPAddress }}"
    
  vars:
    F5_Nodes: "{{F5_Node_Names}}"
    F5_Node_State: "{{F5_Node_Status}}"

  tasks:
    - name: DISABLE NODES
      bigip_node:
        name: "{{item}}"
        state: "disabled"
      when: F5_Node_State|lower  == "disabled"
      with_items: "{{ F5_Nodes }}"

    - name: ENABLE NODES
      bigip_node:
        name: "{{item}}"
        state: "enabled"
      when: F5_Node_State|lower == "enabled"
      with_items: "{{ F5_Nodes }}
